name: Auto-update Pre-commit
on:
  schedule:
    - cron: '0 9 1 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate