name: Format (auto-fix)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install black

      - name: Verify Black installation
        run: python -m black --version

      - name: Auto-format with Black (push)
        if: github.event_name == 'push'
        run: |
          python -m black .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: auto-format with Black" || echo "No changes to commit"
          git push

      - name: Check formatting with Black (PRs)
        if: github.event_name == 'pull_request'
        run: python -m black . --check --diff
