name: Format (auto-fix)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write        # needed to commit/push fixes on 'push' events
  pull-requests: write   # allows PR annotations

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Show Black version
        run: python -m black --version

      # On pushes to main: auto-format, commit, and push any changes
      - name: Auto-format with Black and commit (push events)
        if: github.event_name == 'push'
        run: |
          set -e
          python -m black .
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "style: auto-format with Black"
            git push
          else
            echo "No formatting changes to commit."
          fi

      # On PRs: check only (no commit), fail if formatting is needed
      - name: Check formatting with Black (PRs)
        if: github.event_name == 'pull_request'
        run: |
          # --check makes it fail if changes are needed (shows diff in logs)
          python -m black . --check --diff
